Repository PDA-Final-Project-Team1/BE, pull requests merged in 2025-03, with the labels that each got.

#37 Feat/#34 유저즐겨찾기
  ET-user/src/main/java/com/team1/etuser/user/controller/UserController.java
  ET-user/src/main/java/com/team1/etuser/user/dto/UserFavoriteStocksRes.java
  ET-user/src/main/java/com/team1/etuser/user/repository/UserFavoriteStockRepository.java
  ET-user/src/main/java/com/team1/etuser/user/service/UserFavoriteService.java
Labels: ✨ Feat

#38 Refactor/#22-설정 파일 JWT 관련 추가사항
  .gitignore
  ET-api-gateway/src/main/java/com/team1/etapigateway/config/SecurityConfig.java
  ET-api-gateway/src/main/java/com/team1/etapigateway/filter/JwtGatewayFilter.java
  ET-api-gateway/src/main/resources/application.yml
  ET-common/src/main/java/com/team1/etcommon/exception/GlobalExceptionHandler.java
  ET-user/src/main/java/com/team1/etuser/user/controller/AuthController.java
  ET-user/src/main/java/com/team1/etuser/user/controller/UserController.java
  ET-user/src/main/java/com/team1/etuser/user/dto/AuthResponseDto.java
  ET-user/src/main/java/com/team1/etuser/user/dto/LoginRequestDto.java
  ET-user/src/main/java/com/team1/etuser/user/dto/SignUpRequestDto.java
  ET-user/src/main/java/com/team1/etuser/user/exception/AuthExceptionHandler.java
  ET-user/src/main/java/com/team1/etuser/user/repository/UserRepository.java
  ET-user/src/main/java/com/team1/etuser/user/security/JwtTokenProvider.java
  ET-user/src/main/java/com/team1/etuser/user/security/SecurityConfig.java
  ET-user/src/main/java/com/team1/etuser/user/service/AuthService.java
  ET-user/src/main/java/com/team1/etuser/user/service/UserService.java
  ET-user/src/main/java/com/team1/etuser/user/service/UserServiceImpl.java
  ET-user/src/main/resources/application.yml
  build.gradle
Labels: 🔨 Refactor

#40 Refacotr/#39-헤더에서 ID받도록 수정
  ET-api-gateway/src/main/java/com/team1/etapigateway/filter/JwtGatewayFilter.java
  ET-user/src/main/java/com/team1/etuser/user/controller/UserController.java
  ET-user/src/main/java/com/team1/etuser/user/service/UserFavoriteService.java
  ET-user/src/main/java/com/team1/etuser/user/service/UserService.java
  ET-user/src/main/java/com/team1/etuser/user/service/UserServiceImpl.java
Labels: 🔨 Refactor

#43 Refacotr/#42-응답에 날짜 추가
  ET-user/src/main/java/com/team1/etuser/user/dto/UserHistoryRes.java
  ET-user/src/main/java/com/team1/etuser/user/repository/UserTradeHistoryRepository.java
Labels: 🔨 Refactor

#45 Feat: 로그인한 유저의 목장 조회
  ET-arcade/src/main/java/com/team1/etarcade/EtArcadeApplication.java
  ET-arcade/src/main/java/com/team1/etarcade/pet/connector/UserFeignConnector.java
  ET-arcade/src/main/java/com/team1/etarcade/pet/controller/PetController.java
  ET-arcade/src/main/java/com/team1/etarcade/pet/dto/UserPetResponseDTO.java
  ET-arcade/src/main/java/com/team1/etarcade/pet/service/PetService.java
  ET-user/src/main/java/com/team1/etuser/user/controller/UserController.java
  ET-user/src/main/java/com/team1/etuser/user/dto/UserPetResponseDto.java
  ET-user/src/main/java/com/team1/etuser/user/repository/UserPetRepository.java
  ET-user/src/main/java/com/team1/etuser/user/service/UserPetService.java
Labels: ✨ Feat

#47 Feat: 로그인한 사용자에게 펫 랜덤 지급
  ET-arcade/src/main/java/com/team1/etarcade/pet/connector/UserFeignConnector.java
  ET-arcade/src/main/java/com/team1/etarcade/pet/controller/PetController.java
  ET-arcade/src/main/java/com/team1/etarcade/pet/dto/PetGrantRequestDTO.java
  ET-arcade/src/main/java/com/team1/etarcade/pet/service/PetService.java
  ET-user/src/main/java/com/team1/etuser/user/controller/FriendController.java
  ET-user/src/main/java/com/team1/etuser/user/controller/UserController.java
  ET-user/src/main/java/com/team1/etuser/user/dto/PetGrantRequestDto.java
  ET-user/src/main/java/com/team1/etuser/user/service/FriendService.java
  ET-user/src/main/java/com/team1/etuser/user/service/UserPetService.java
Labels: ✨ Feat

#54 Feat: 아이디 조회 기능 구현
  ET-user/src/main/java/com/team1/etuser/user/controller/UserController.java
  ET-user/src/main/java/com/team1/etuser/user/dto/UserResponseDto.java
  ET-user/src/main/java/com/team1/etuser/user/repository/FriendRepository.java
  ET-user/src/main/java/com/team1/etuser/user/service/FriendService.java
  ET-user/src/main/java/com/team1/etuser/user/service/UserService.java
  ET-user/src/main/java/com/team1/etuser/user/service/UserServiceImpl.java
Labels: ✨ Feat

#56 Feat/#7 kafka pub/sub
  ET-core/src/main/java/com/team1/etcore/chart/ChartDataController.java
  ET-core/src/main/java/com/team1/etcore/chart/ChartDataService.java
  ET-core/src/main/java/com/team1/etcore/chart/dto/StockResponseDto.java
  ET-core/src/main/java/com/team1/etcore/stock/controller/SseController.java
  ET-core/src/main/java/com/team1/etcore/stock/dto/AskStockPriceDto.java
  ET-core/src/main/java/com/team1/etcore/stock/dto/TestDTO.java
  ET-core/src/main/java/com/team1/etcore/stock/service/KafkaStockConsumer.java
  ET-core/src/main/java/com/team1/etcore/stock/service/SseService.java
  ET-pipeline/src/main/java/com/team1/etpipeline/kafka/koreaInvestAPI/ApprovalService.java
  ET-pipeline/src/main/java/com/team1/etpipeline/kafka/koreaInvestAPI/KoreaInvestmentWebSocketClient.java
  ET-pipeline/src/main/resources/application.yml
Labels: ✨ Feat

#58 Feat: 기업명 조회
  ET-core/src/main/java/com/team1/etcore/stock/controller/StockController.java
  ET-core/src/main/java/com/team1/etcore/stock/dto/StockResponseDTO.java
  ET-core/src/main/java/com/team1/etcore/stock/service/StockService.java
  ET-core/src/main/java/com/team1/etcore/stock/service/StockServiceImpl.java
  ET-core/src/main/java/com/team1/etcore/stock/util/HangulUtils.java
  ET-core/src/main/java/com/team1/etcore/stock/util/StockData.java
  ET-core/src/main/java/com/team1/etcore/stock/util/StockData.json
  ET-core/src/main/java/com/team1/etcore/stock/util/Trie.java
Labels: ✨ Feat

#60 Feat/#55 매매
  ET-common/src/main/java/com/team1/etcommon/redis/RedisConfig.java
  ET-core/src/main/java/com/team1/etcore/EtCoreApplication.java
  ET-core/src/main/java/com/team1/etcore/trade/client/UserTradeHistoryClient.java
  ET-core/src/main/java/com/team1/etcore/trade/controller/TradeController.java
  ET-core/src/main/java/com/team1/etcore/trade/dto/Position.java
  ET-core/src/main/java/com/team1/etcore/trade/dto/TestDTO.java
  ET-core/src/main/java/com/team1/etcore/trade/dto/TradeReq.java
  ET-core/src/main/java/com/team1/etcore/trade/dto/TradeRes.java
  ET-core/src/main/java/com/team1/etcore/trade/dto/TradeStatus.java
  ET-core/src/main/java/com/team1/etcore/trade/service/TradeConsumer.java
  ET-core/src/main/java/com/team1/etcore/trade/service/TradeService.java
  ET-pipeline/src/main/java/com/team1/etpipeline/kafka/koreaInvestAPI/KoreaInvestmentWebSocketClient.java
  ET-user/src/main/java/com/team1/etuser/user/controller/UserFeignController.java
  ET-user/src/main/java/com/team1/etuser/user/domain/TradeStatus.java
  ET-user/src/main/java/com/team1/etuser/user/domain/UserAdditionalInfo.java
  ET-user/src/main/java/com/team1/etuser/user/domain/UserStock.java
  ET-user/src/main/java/com/team1/etuser/user/domain/UserTradeHistory.java
  ET-user/src/main/java/com/team1/etuser/user/dto/feign/TradeReq.java
  ET-user/src/main/java/com/team1/etuser/user/dto/feign/TradeRes.java
  ET-user/src/main/java/com/team1/etuser/user/repository/UserAdditionalInfoRepository.java
  ET-user/src/main/java/com/team1/etuser/user/repository/UserStockRepository.java
  ET-user/src/main/java/com/team1/etuser/user/service/UserAdditionalService.java
  ET-user/src/main/java/com/team1/etuser/user/service/UserServiceImpl.java
  ET-user/src/main/java/com/team1/etuser/user/service/UserStockService.java
  ET-user/src/main/java/com/team1/etuser/user/service/UserTradeHistoryService.java
Labels: ✨ Feat

#62 Refactor: 거래내역에 업데이트 날짜 및 상태 값 추가
  ET-user/src/main/java/com/team1/etuser/user/dto/UserHistoryRes.java
  ET-user/src/main/java/com/team1/etuser/user/repository/UserTradeHistoryRepository.java
  ET-user/src/main/java/com/team1/etuser/user/service/UserServiceImpl.java
Labels: 🔨 Refactor

#64 Feat: 거래 취소
  ET-core/src/main/java/com/team1/etcore/trade/client/UserTradeHistoryClient.java
  ET-core/src/main/java/com/team1/etcore/trade/controller/TradeController.java
  ET-core/src/main/java/com/team1/etcore/trade/dto/TradeCancelReq.java
  ET-core/src/main/java/com/team1/etcore/trade/dto/TradeHistoryRedisRes.java
  ET-core/src/main/java/com/team1/etcore/trade/service/TradeService.java
  ET-user/src/main/java/com/team1/etuser/user/controller/UserFeignController.java
Labels: ✨ Feat

#66 Refactor: 아이디 조회
  ET-user/src/main/java/com/team1/etuser/user/dto/UserResponseDto.java
  ET-user/src/main/java/com/team1/etuser/user/service/UserServiceImpl.java
Labels: 🔨 Refactor

#69 Refactor: 펫 지급시 반환 값 수정
  ET-arcade/src/main/java/com/team1/etarcade/pet/connector/UserFeignConnector.java
  ET-arcade/src/main/java/com/team1/etarcade/pet/controller/PetController.java
  ET-arcade/src/main/java/com/team1/etarcade/pet/dto/PetGrantResponseDTO.java
  ET-arcade/src/main/java/com/team1/etarcade/pet/repository/PetRepository.java
  ET-arcade/src/main/java/com/team1/etarcade/pet/service/PetService.java
  ET-user/src/main/java/com/team1/etuser/user/controller/UserController.java
  ET-user/src/main/java/com/team1/etuser/user/service/UserPetService.java
Labels: 🔨 Refactor

#72 Feat/#55 매매
  ET-common/src/main/java/com/team1/etcommon/redis/RedisConfig.java
  ET-core/src/main/java/com/team1/etcore/trade/client/UserTradeHistoryClient.java
  ET-core/src/main/java/com/team1/etcore/trade/dto/QuoteDTO.java
  ET-core/src/main/java/com/team1/etcore/trade/dto/TradeRes.java
  ET-core/src/main/java/com/team1/etcore/trade/service/TradeConsumer.java
  ET-core/src/main/java/com/team1/etcore/trade/service/TradeService.java
  ET-core/src/main/java/com/team1/etcore/trade/service/TradeSettlement.java
  ET-core/src/test/java/com/team1/etcore/trade/service/TradeServiceTest.java
  ET-pipeline/src/main/java/com/team1/etpipeline/kafka/koreaInvestAPI/KoreaInvestmentWebSocketClient.java
  ET-user/src/main/java/com/team1/etuser/user/controller/UserFeignController.java
  build.gradle
Labels: ✨ Feat

#74 Refactor: sse 주석 처리
  ET-core/src/main/java/com/team1/etcore/trade/service/TradeService.java
Labels: 🔨 Refactor

#77 Feat/#75 거래체결 알림
  ET-core/src/main/java/com/team1/etcore/stock/controller/SseController.java
  ET-core/src/main/java/com/team1/etcore/stock/service/SseService.java
Labels: ✨ Feat

#79 feat: 거래 체결 알림
  ET-core/src/main/java/com/team1/etcore/trade/service/TradeService.java
Labels: ✨ Feat

#82 Refactor/#73-Kafka를 이용해 정산하도록 수정
  .gitignore
  ET-core/src/main/java/com/team1/etcore/global/config/KafkaProducerConfig.java
  ET-core/src/main/java/com/team1/etcore/trade/client/UserTradeHistoryClient.java
  ET-core/src/main/java/com/team1/etcore/trade/controller/TradeController.java
  ET-core/src/main/java/com/team1/etcore/trade/dto/SettlementDTO.java
  ET-core/src/main/java/com/team1/etcore/trade/service/TradeConsumer.java
  ET-core/src/main/java/com/team1/etcore/trade/service/TradeService.java
  ET-core/src/main/java/com/team1/etcore/trade/service/TradeSettlement.java
  ET-pipeline/src/main/java/com/team1/etpipeline/ManualH0STASP0App.java
  ET-user/src/main/java/com/team1/etuser/EtUserApplication.java
  ET-user/src/main/java/com/team1/etuser/user/config/KafkaConsumerConfig.java
  ET-user/src/main/java/com/team1/etuser/user/config/KafkaProducerConfig.java
  ET-user/src/main/java/com/team1/etuser/user/dto/SettlementDTO.java
  ET-user/src/main/java/com/team1/etuser/user/service/SettlementConsumer.java
  ET-user/src/main/java/com/team1/etuser/user/service/SettlementService.java
  ET-user/src/main/java/com/team1/etuser/user/service/UserAdditionalService.java
  ET-user/src/main/java/com/team1/etuser/user/service/UserStockService.java
  ET-user/src/main/java/com/team1/etuser/user/service/UserTradeHistoryService.java
  build.gradle
Labels: 🔨 Refactor

#86 Refactor: 환경 변수 설정 및 Dockerfile 생성
  .gitignore
  ET-pipeline/Dockerfile
  ET-pipeline/src/main/resources/korea-investment.properties
Labels: 🔨 Refactor

#89 Fix/#88 sse
  ET-api-gateway/src/main/java/com/team1/etapigateway/config/SecurityConfig.java
  ET-api-gateway/src/main/resources/application.yml
  ET-core/src/main/java/com/team1/etcore/stock/controller/SseController.java
  ET-core/src/main/java/com/team1/etcore/stock/service/SseService.java
Labels: 🐞 Fix

#96 Feat/#93 도감 조회
  ET-user/src/main/java/com/team1/etuser/user/controller/UserController.java
Labels: 📃 Docs, 🔨 Refactor

#98 Refactor: 구독 목록 조회에 uid값 반환
  ET-user/src/main/java/com/team1/etuser/user/dto/FriendRes.java
  ET-user/src/main/java/com/team1/etuser/user/dto/FriendResponseDto.java
  ET-user/src/main/java/com/team1/etuser/user/dto/SubscriptionResponseDto.java
  ET-user/src/main/java/com/team1/etuser/user/service/FriendService.java
Labels: 🔨 Refactor

#99 Refactor: 구독한 유저의 목장 조회 수정
  ET-arcade/src/main/java/com/team1/etarcade/pet/dto/UserFriendResponseDTO.java
  ET-arcade/src/main/java/com/team1/etarcade/pet/service/PetService.java
Labels: 🔨 Refactor

#107 Refactor: 주식 데이터 초기 로딩 방식 변경
  ET-core/src/main/java/com/team1/etcore/stock/config/CacheConfig.java
  ET-core/src/main/java/com/team1/etcore/stock/dto/StockResponseDTO.java
  ET-core/src/main/java/com/team1/etcore/stock/initializer/StockInitializer.java
  ET-core/src/main/java/com/team1/etcore/stock/service/StockCache.java
  ET-core/src/main/java/com/team1/etcore/stock/service/StockServiceImpl.java
Labels: 🔨 Refactor

#108 Feat/#102-알림 토픽 발행 및 DTO 타입 변경
  ET-core/src/main/java/com/team1/etcore/trade/client/UserTradeHistoryClient.java
  ET-core/src/main/java/com/team1/etcore/trade/dto/QuoteDTO.java
  ET-core/src/main/java/com/team1/etcore/trade/dto/SettlementDTO.java
  ET-core/src/main/java/com/team1/etcore/trade/dto/TradeReq.java
  ET-core/src/main/java/com/team1/etcore/trade/dto/TradeRes.java
  ET-core/src/main/java/com/team1/etcore/trade/service/TradeConsumer.java
  ET-core/src/main/java/com/team1/etcore/trade/service/TradeService.java
  ET-user/src/main/java/com/team1/etuser/user/dto/TradeResult.java
  ET-user/src/main/java/com/team1/etuser/user/service/SettlementService.java
Labels: ✨ Feat

#110 Refactor/#100-historyId 및 종목 이미지 추가
  ET-user/src/main/java/com/team1/etuser/user/dto/UserHistoryRes.java
  ET-user/src/main/java/com/team1/etuser/user/repository/UserTradeHistoryRepository.java
  ET-user/src/main/java/com/team1/etuser/user/service/UserServiceImpl.java
Labels: 🔨 Refactor

#112 Refactor/#111-userId추가
  ET-user/src/main/java/com/team1/etuser/user/dto/TradeResult.java
  ET-user/src/main/java/com/team1/etuser/user/service/SettlementService.java
Labels: 🔨 Refactor

#113 [FEAT] EggService 유저알 검증 로직 추가
  ET-arcade/src/main/java/com/team1/etarcade/egg/connector/StockFeignConnector.java
  ET-arcade/src/main/java/com/team1/etarcade/egg/connector/UserFeignConnector.java
  ET-arcade/src/main/java/com/team1/etarcade/egg/dto/StockAmountDTO.java
  ET-arcade/src/main/java/com/team1/etarcade/egg/dto/UserFeignStockRes.java
  ET-arcade/src/main/java/com/team1/etarcade/egg/repository/EggRepository.java
  ET-arcade/src/main/java/com/team1/etarcade/egg/service/EggService.java
Labels: 🔨 Refactor

#116 Feat/#115-보유주식 전날종가 및 특정 주식의 전날 종가 조회
  ET-user/src/main/java/com/team1/etuser/user/config/RestTemplateConfig.java
  ET-user/src/main/java/com/team1/etuser/user/controller/UserController.java
  ET-user/src/main/java/com/team1/etuser/user/dto/StockPreviousCloseDto.java
  ET-user/src/main/java/com/team1/etuser/user/repository/UserStockRepository.java
  ET-user/src/main/java/com/team1/etuser/user/service/UserStockService.java
  build.gradle
Labels: ✨ Feat

#117 Refactor: 거래 체결 알림 수정
  ET-core/src/main/java/com/team1/etcore/stock/controller/SseController.java
  ET-core/src/main/java/com/team1/etcore/stock/dto/TradeResult.java
  ET-core/src/main/java/com/team1/etcore/stock/service/SseService.java
  ET-core/src/main/java/com/team1/etcore/trade/service/TradeService.java
  ET-user/src/main/java/com/team1/etuser/user/service/SettlementConsumer.java
Labels: 🔨 Refactor

#118 Refactor: 거래 체결 알림 수정
  ET-core/src/main/java/com/team1/etcore/stock/controller/SseController.java
Labels: 🔨 Refactor

#122 Refactor: 거래 체결 알림 수정
  ET-core/src/main/java/com/team1/etcore/stock/dto/TradeResult.java
  ET-core/src/main/java/com/team1/etcore/stock/repository/StockRepository.java
  ET-core/src/main/java/com/team1/etcore/stock/service/SseService.java
Labels: 🔨 Refactor

#123 Feat/#20 알부화 및 소수점주식 지급
  ET-arcade/src/main/java/com/team1/etarcade/egg/connector/StockFeignConnector.java
  ET-arcade/src/main/java/com/team1/etarcade/egg/connector/UserFeignConnector.java
  ET-arcade/src/main/java/com/team1/etarcade/egg/controller/EggController.java
  ET-arcade/src/main/java/com/team1/etarcade/egg/dto/EggHatchingRes.java
  ET-arcade/src/main/java/com/team1/etarcade/egg/dto/StockNameAndCodeDTO.java
  ET-arcade/src/main/java/com/team1/etarcade/egg/dto/StockPreviousCloseDto.java
  ET-arcade/src/main/java/com/team1/etarcade/egg/dto/StockPriceDTO.java
  ET-arcade/src/main/java/com/team1/etarcade/egg/service/EggService.java
  ET-core/src/main/java/com/team1/etcore/stock/controller/StockController.java
  ET-core/src/main/java/com/team1/etcore/stock/dto/StockDataDTO.java
  ET-core/src/main/java/com/team1/etcore/stock/dto/StockNameAndCodeDTO.java
  ET-core/src/main/java/com/team1/etcore/stock/service/StockService.java
  ET-core/src/main/java/com/team1/etcore/stock/service/StockServiceImpl.java
  ET-user/src/main/java/com/team1/etuser/user/domain/User.java
  ET-user/src/main/java/com/team1/etuser/user/service/UserStockService.java
Labels: ✨ Feat

#124 Refactor: 주식 초기 데이터 누락 추가
  ET-core/src/main/resources/stock/StockData.json
Labels: 🔨 Refactor

#128 Refactor/#127-DB인덱스 적용
  ET-arcade/src/main/java/com/team1/etarcade/egg/domain/Egg.java
  ET-arcade/src/main/java/com/team1/etarcade/quiz/domain/Quiz.java
  ET-user/src/main/java/com/team1/etuser/stock/controller/UserStockController.java
  ET-user/src/main/java/com/team1/etuser/stock/domain/UserFavoriteStock.java
  ET-user/src/main/java/com/team1/etuser/stock/domain/UserStock.java
  ET-user/src/main/java/com/team1/etuser/stock/service/UserFavoriteService.java
  ET-user/src/main/java/com/team1/etuser/user/domain/User.java
Labels: 🔨 Refactor

#130 Refactor: 본인 아이디 조회 안되게 변경
  ET-user/src/main/java/com/team1/etuser/user/controller/UserController.java
  ET-user/src/main/java/com/team1/etuser/user/service/UserService.java
  ET-user/src/main/java/com/team1/etuser/user/service/UserServiceImpl.java
Labels: 🔨 Refactor

#133 Refactor: 펫 지급 시 이름도 반환되게 수정
  ET-arcade/src/main/java/com/team1/etarcade/pet/PetController.java
  ET-arcade/src/main/java/com/team1/etarcade/pet/dto/PetGrantRes.java
Labels: 🔨 Refactor

#135 [FIX] 알부화 CRUD 타입, 퀴즈 응답 변경
  ET-arcade/src/main/java/com/team1/etarcade/EtArcadeApplication.java
  ET-arcade/src/main/java/com/team1/etarcade/egg/EggController.java
  ET-arcade/src/main/java/com/team1/etarcade/quiz/QuizService.java
  ET-arcade/src/main/java/com/team1/etarcade/quiz/dto/UserPointRes.java
Labels: 🐞 Fix

#136 [FIX] 이미푼퀴즈에 퀴즈 답 반환 추가
  ET-arcade/src/main/java/com/team1/etarcade/quiz/QuizService.java
  ET-arcade/src/main/java/com/team1/etarcade/quiz/dto/SolvedQuizRes.java
Labels: 🐞 Fix

#137 [FIX] 획득 포인트 변경
  ET-arcade/src/main/java/com/team1/etarcade/quiz/QuizService.java
Labels: 🐞 Fix

#139 version 0.0.3
  ET-api-gateway/src/main/java/com/team1/etapigateway/config/SecurityConfig.java
  ET-arcade/src/main/java/com/team1/etarcade/EtArcadeApplication.java
  ET-arcade/src/main/java/com/team1/etarcade/egg/EggController.java
  ET-arcade/src/main/java/com/team1/etarcade/pet/PetController.java
  ET-arcade/src/main/java/com/team1/etarcade/pet/dto/PetGrantRes.java
  ET-arcade/src/main/java/com/team1/etarcade/quiz/QuizService.java
  ET-arcade/src/main/java/com/team1/etarcade/quiz/dto/SolvedQuizRes.java
  ET-arcade/src/main/java/com/team1/etarcade/quiz/dto/UserPointRes.java
  ET-core/src/main/java/com/team1/etcore/stock/service/KafkaStockConsumer.java
  ET-user/src/main/java/com/team1/etuser/stock/controller/UserStockController.java
  ET-user/src/main/java/com/team1/etuser/stock/repository/UserFavoriteStockRepository.java
  ET-user/src/main/java/com/team1/etuser/stock/repository/UserStockRepository.java
  ET-user/src/main/java/com/team1/etuser/stock/service/UserStockService.java
Labels: ✨ Feat

#140 Refactor: cors 설정 수정
  ET-api-gateway/src/main/java/com/team1/etapigateway/config/SecurityConfig.java
Labels: 🔨 Refactor

#146 Refactor: 재연결 수정
  ET-pipeline/src/main/java/com/team1/etpipeline/kafka/koreaInvestAPI/KoreaInvestmentWebSocketClient.java
Labels: ✨ Feat

#147 Feat: 거래내역 필터, 페이징
  ET-user/src/main/java/com/team1/etuser/stock/controller/TradeHistoryController.java
  ET-user/src/main/java/com/team1/etuser/stock/repository/UserTradeHistoryRepository.java
  ET-user/src/main/java/com/team1/etuser/user/service/UserService.java
  ET-user/src/main/java/com/team1/etuser/user/service/UserServiceImpl.java
Labels: ✨ Feat

#148 Refactor: 거래내역 내림차순 정렬
  ET-user/src/main/java/com/team1/etuser/stock/repository/UserTradeHistoryRepository.java
Labels: 🔨 Refactor

#149 Version 1.0.0
  ET-pipeline/src/main/java/com/team1/etpipeline/kafka/koreaInvestAPI/KoreaInvestmentWebSocketClient.java
  ET-user/src/main/java/com/team1/etuser/stock/controller/TradeHistoryController.java
  ET-user/src/main/java/com/team1/etuser/stock/repository/UserTradeHistoryRepository.java
  ET-user/src/main/java/com/team1/etuser/user/service/UserService.java
  ET-user/src/main/java/com/team1/etuser/user/service/UserServiceImpl.java
Labels: ✨ Feat

#151 Fix/#150-stockData.json 경로 수정
  ET-core/src/main/java/com/team1/etcore/stock/service/StockServiceImpl.java
Labels: 🐞 Fix

#152 알 부화 에러 수정
  ET-core/src/main/java/com/team1/etcore/stock/service/StockServiceImpl.java
Labels: 🐞 Fix

#154 Fix: 아이디 검색 시, 구독 여부 올바르게 반환 하도록 수정
  ET-user/src/main/java/com/team1/etuser/friend/FriendRepository.java
  ET-user/src/main/java/com/team1/etuser/friend/FriendService.java
  ET-user/src/main/java/com/team1/etuser/user/service/UserServiceImpl.java
Labels: 🐞 Fix

#156 Fix: 거래 체결 알림 수정
  ET-core/src/main/java/com/team1/etcore/stock/service/SseService.java
Labels: 🐞 Fix

#158 Fix/#157-매도 시 예치금 조회하는 잘못된 로직 수정
  ET-core/src/main/java/com/team1/etcore/trade/service/TradeService.java
Labels: 🐞 Fix

#159 Dev
  ET-core/src/main/java/com/team1/etcore/stock/service/SseService.java
  ET-core/src/main/java/com/team1/etcore/trade/service/TradeService.java
  ET-user/src/main/java/com/team1/etuser/friend/FriendRepository.java
  ET-user/src/main/java/com/team1/etuser/friend/FriendService.java
  ET-user/src/main/java/com/team1/etuser/user/service/UserServiceImpl.java
Labels: 🐞 Fix

#161 Fix: 거래 체결 알림 수정
  ET-core/src/main/java/com/team1/etcore/stock/service/SseService.java
Labels: 🐞 Fix

#163 Refactor/#160-부화 응답 수정 및 알부화가능 스케줄링
  ET-arcade/src/main/java/com/team1/etarcade/egg/EggService.java
  ET-arcade/src/main/java/com/team1/etarcade/egg/config/SchedulerConfig.java
  ET-arcade/src/main/java/com/team1/etarcade/egg/domain/Egg.java
  ET-arcade/src/main/java/com/team1/etarcade/egg/dto/StockInfoRes.java
  ET-core/src/main/java/com/team1/etcore/stock/dto/StockInfoRes.java
  ET-core/src/main/java/com/team1/etcore/stock/repository/StockRepository.java
  ET-core/src/main/java/com/team1/etcore/stock/service/StockServiceImpl.java
Labels: 🔨 Refactor

#167 Feat/#166-거래횟수 조회
  ET-user/src/main/java/com/team1/etuser/stock/controller/TradeHistoryController.java
  ET-user/src/main/java/com/team1/etuser/stock/dto/TradeCountRes.java
  ET-user/src/main/java/com/team1/etuser/stock/repository/UserTradeHistoryRepository.java
  ET-user/src/main/java/com/team1/etuser/stock/service/TradeHistoryService.java
Labels: ✨ Feat

#168 Dev
  ET-user/src/main/java/com/team1/etuser/stock/controller/TradeHistoryController.java
  ET-user/src/main/java/com/team1/etuser/stock/controller/UserStockController.java
  ET-user/src/main/java/com/team1/etuser/stock/dto/TradeCountRes.java
  ET-user/src/main/java/com/team1/etuser/stock/repository/UserStockRepository.java
  ET-user/src/main/java/com/team1/etuser/stock/repository/UserTradeHistoryRepository.java
  ET-user/src/main/java/com/team1/etuser/stock/service/TradeHistoryService.java
Labels: ✨ Feat, 🔨 Refactor

#169 fix : 관심종목 종가데이터 추가 수정
  ET-user/src/main/java/com/team1/etuser/stock/repository/UserFavoriteStockRepository.java
  ET-user/src/main/java/com/team1/etuser/stock/service/UserStockService.java
Labels: 🐞 Fix

#172 Refacotr/#170 실시간데이터 SSE
  ET-core/src/main/java/com/team1/etcore/EtCoreApplication.java
  ET-core/src/main/java/com/team1/etcore/stock/controller/SseController.java
  ET-core/src/main/java/com/team1/etcore/stock/dto/ConnectRes.java
  ET-core/src/main/java/com/team1/etcore/stock/dto/TradeResultRes.java
  ET-core/src/main/java/com/team1/etcore/stock/dto/TradeStockPriceReq.java
  ET-core/src/main/java/com/team1/etcore/stock/service/DataBuffer.java
  ET-core/src/main/java/com/team1/etcore/stock/service/DataFlusher.java
  ET-core/src/main/java/com/team1/etcore/stock/service/KafkaStockConsumer.java
  ET-core/src/main/java/com/team1/etcore/stock/service/SseService.java
  ET-pipeline/src/main/java/com/team1/etpipeline/kafka/koreaInvestAPI/KoreaInvestmentWebSocketClient.java
  build.gradle
Labels: 🐞 Fix, 🔨 Refactor
